[build]
base="droom-app"
publish="build/"
command="npm run build"

[[redirects]]
from="/*"
to="/index.html"
status=200

[[redirects]]
  from = "/login"
  to = "https://cors-anywhere.herokuapp.com/droom-pt-bw.herokuapp.com/seekers/*"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"